import AppKit
import CryptoKit
import Foundation
import UniformTypeIdentifiers
import Vision

/// Watches the system clipboard and turns every copy into a `Clip`.
///
/// macOS posts no notification when the pasteboard changes, so we poll
/// `changeCount` — one integer, cheap enough to read several times a second, and
/// the approach every app of this kind ends up using.
@MainActor
final class ClipboardMonitor {
    private let store: ClipStore
    private let preferences: Preferences
    private var timer: Timer?
    private var screenshotTimer: Timer?
    private var lastChangeCount: Int
    /// The pasteboard count after an iPaste write has completed. A write can
    /// produce more than one change, so never predict this value in advance.
    private var ignoredChangesThrough: Int?
    /// Kept for Text Capture if the polling timer observes the copy before the
    /// explicit import callback runs.
    private var explicitCaptureChangeCount: Int?
    private var explicitCaptureBaseline: Int?
    private var knownScreenshotPaths = Set<String>()

    /// Types other apps use to say "do not remember this" — password managers and such.
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword")
    ]

    var onCapture: ((Clip) -> Void)?
    var onSensitiveCapture: ((Clip) -> Void)?

    init(store: ClipStore, preferences: Preferences) {
        self.store = store
        self.preferences = preferences
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start(interval: TimeInterval = 0.35) {
        stop()
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // .common so polling doesn't stall while the user holds a menu open.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer

        // Backfill OCR for images captured before Vision support was added.
        for clip in store.orderedClips where clip.kind == .image && clip.ocrText == nil {
            scheduleOCR(for: clip)
        }

        startScreenshotMonitor()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        screenshotTimer?.invalidate()
        screenshotTimer = nil
    }

    /// Called after iPaste finishes writing to the pasteboard.
    func ignoreOwnChanges(through changeCount: Int) {
        ignoredChangesThrough = changeCount
        explicitCaptureChangeCount = nil
    }

    func prepareForExplicitCapture() {
        explicitCaptureBaseline = NSPasteboard.general.changeCount
        explicitCaptureChangeCount = nil
    }

    // MARK: - Capture

    private func poll() {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }

        if let ignored = ignoredChangesThrough {
            // If another app changed the pasteboard after our write but before
            // the next poll, capture that newer content instead of swallowing it.
            ignoredChangesThrough = nil
            if changeCount <= ignored {
                lastChangeCount = changeCount
                return
            }
        }

        if let baseline = explicitCaptureBaseline, changeCount > baseline {
            explicitCaptureBaseline = nil
            explicitCaptureChangeCount = changeCount
            lastChangeCount = changeCount
            return
        }
        lastChangeCount = changeCount
        guard !isConcealed(pasteboard) else { return }
        guard !preferences.ignores(bundleID: NSWorkspace.shared.frontmostApplication?.bundleIdentifier) else {
            return
        }
        let app = NSWorkspace.shared.frontmostApplication
        if app?.bundleIdentifier != Bundle.main.bundleIdentifier,
           let image = imageFromPasteboard(pasteboard),
           let data = image.tiffRepresentation {
            captureImage(
                image,
                data: data,
                sourceAppName: app?.localizedName,
                sourceBundleID: app?.bundleIdentifier
            )
            return
        }

        guard let clip = makeClip(from: pasteboard) else { return }

        _ = storeCapturedClip(clip)
    }

    /// Imports the current pasteboard after an explicit capture action such as
    /// Text Capture. It only succeeds when the pasteboard actually changed, so
    /// invoking the action with no selection cannot duplicate the previous clip.
    @discardableResult
    func captureCurrentPasteboard(textOnly: Bool = false) -> Bool {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        let isExplicitChange = explicitCaptureChangeCount == changeCount
        guard changeCount != lastChangeCount || isExplicitChange else {
            // A failed selection copy must not suppress the user's next normal copy.
            explicitCaptureBaseline = nil
            explicitCaptureChangeCount = nil
            return false
        }
        lastChangeCount = changeCount
        explicitCaptureBaseline = nil
        explicitCaptureChangeCount = nil

        guard !isConcealed(pasteboard),
              !preferences.ignores(bundleID: NSWorkspace.shared.frontmostApplication?.bundleIdentifier)
        else { return false }

        if !textOnly,
           let image = imageFromPasteboard(pasteboard),
           let data = image.tiffRepresentation {
            let app = NSWorkspace.shared.frontmostApplication
            captureImage(image, data: data, sourceAppName: app?.localizedName, sourceBundleID: app?.bundleIdentifier)
            return true
        }

        let clip: Clip?
        if textOnly {
            clip = makeTextClip(from: pasteboard)
        } else {
            clip = makeClip(from: pasteboard)
        }
        guard let clip else { return false }

        return storeCapturedClip(clip)
    }

    /// Captures content dropped directly on the notch trigger panel.
    @discardableResult
    func captureDroppedPasteboard(_ pasteboard: NSPasteboard) -> Bool {
        guard !isConcealed(pasteboard) else { return false }
        if let image = imageFromPasteboard(pasteboard), let data = image.tiffRepresentation {
            captureImage(image, data: data, sourceAppName: "Drag & Drop", sourceBundleID: "com.ipaste.drag-drop")
            return true
        }
        guard let clip = makeClip(from: pasteboard, allowSelfSource: true) else { return false }
        return storeCapturedClip(clip)
    }

    /// Captures content dropped inside the SwiftUI shelf. Item providers are
    /// asynchronous, so the shelf reports success immediately and stores the
    /// resolved item on the main actor when the provider finishes loading it.
    @discardableResult
    func captureDroppedProviders(_ providers: [NSItemProvider]) -> Bool {
        guard let provider = providers.first else { return false }

        if provider.hasItemConformingToTypeIdentifier(UTType.fileURL.identifier) {
            provider.loadObject(ofClass: NSURL.self) { [weak self] object, _ in
                guard let url = (object as? NSURL)?.absoluteURL else { return }
                DispatchQueue.main.async { [weak self] in
                    self?.captureDroppedFile(url)
                }
            }
            return true
        }

        if provider.hasItemConformingToTypeIdentifier(UTType.image.identifier) {
            provider.loadObject(ofClass: NSImage.self) { [weak self] object, _ in
                guard let image = object as? NSImage else { return }
                DispatchQueue.main.async { [weak self] in
                    self?.captureDroppedImage(image)
                }
            }
            return true
        }

        if provider.hasItemConformingToTypeIdentifier(UTType.text.identifier) {
            provider.loadObject(ofClass: NSString.self) { [weak self] object, _ in
                guard let text = (object as? NSString) as String? else { return }
                DispatchQueue.main.async { [weak self] in
                    self?.captureDroppedText(text)
                }
            }
            return true
        }

        return false
    }

    // MARK: - Automatic screenshots

    /// macOS saves ⌘⇧4 captures as files instead of putting them on the
    /// pasteboard. Watch the two standard screenshot locations so those
    /// captures become image clips as well.
    private func startScreenshotMonitor() {
        knownScreenshotPaths = Set(screenshotURLs().map(\.path))
        screenshotTimer?.invalidate()
        screenshotTimer = Timer(timeInterval: 2.0, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.pollScreenshots() }
        }
        if let screenshotTimer {
            RunLoop.main.add(screenshotTimer, forMode: .common)
        }
    }

    private func pollScreenshots() {
        let urls = screenshotURLs()
        knownScreenshotPaths.formIntersection(Set(urls.map(\.path)))
        for url in urls where !knownScreenshotPaths.contains(url.path) {
            guard let image = NSImage(contentsOf: url),
                  let data = try? Data(contentsOf: url),
                  !data.isEmpty
            else { continue }

            knownScreenshotPaths.insert(url.path)
            let resourceValues = try? url.resourceValues(forKeys: [.creationDateKey])
            let createdAt = resourceValues?.creationDate ?? Date()
            captureImage(image, data: data, sourceAppName: "Screenshot", sourceBundleID: "com.apple.screencapture", createdAt: createdAt)
        }
    }

    private func screenshotURLs() -> [URL] {
        let fileManager = FileManager.default
        let desktop = fileManager.urls(for: .desktopDirectory, in: .userDomainMask).first
        let screenshots = fileManager.urls(for: .picturesDirectory, in: .userDomainMask)
            .first?.appendingPathComponent("Screenshots", isDirectory: true)

        return [desktop, screenshots]
            .compactMap { $0 }
            .flatMap { directory -> [URL] in
                guard let files = try? fileManager.contentsOfDirectory(
                    at: directory,
                    includingPropertiesForKeys: [.isRegularFileKey, .creationDateKey],
                    options: [.skipsHiddenFiles]
                ) else { return [] }

                let isScreenshotFolder = directory.lastPathComponent == "Screenshots"
                return files.filter { url in
                    guard let isRegular = try? url.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile,
                          isRegular == true
                    else { return false }
                    let ext = url.pathExtension.lowercased()
                    guard ["png", "jpg", "jpeg"].contains(ext) else { return false }
                    return isScreenshotFolder || Self.looksLikeScreenshotFilename(url.deletingPathExtension().lastPathComponent)
                }
            }
    }

    private nonisolated static func looksLikeScreenshotFilename(_ name: String) -> Bool {
        let lowercased = name.lowercased()
        return [
            "screen shot", "screenshot", "captură de ecran", "captura de ecran",
            "截屏", "снимок экрана"
        ].contains { lowercased.hasPrefix($0) }
    }

    private func isConcealed(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { Self.concealedTypes.contains($0) }
    }

    private func makeClip(from pasteboard: NSPasteboard, allowSelfSource: Bool = false) -> Clip? {
        let app = NSWorkspace.shared.frontmostApplication
        var appName = app?.localizedName
        var bundleID = app?.bundleIdentifier

        // Never capture ourselves.
        if bundleID == Bundle.main.bundleIdentifier {
            guard allowSelfSource else { return nil }
            appName = "Drag & Drop"
            bundleID = "com.ipaste.drag-drop"
        }

        // Files come first: a file copied in Finder also arrives as text and as an image.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path).joined(separator: "\n")
            return Clip(
                kind: urls.count > 1 ? .multi : .file,
                text: paths,
                sourceAppName: appName,
                sourceBundleID: bundleID,
                fingerprint: Self.fingerprint(paths),
                byteSize: urls.reduce(0) { $0 + fileSize(of: $1) }
            )
        }

        if let string = pasteboard.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }
            return Clip(
                kind: Self.detectKind(of: trimmed, bundleID: bundleID),
                text: string,
                sourceAppName: appName,
                sourceBundleID: bundleID,
                fingerprint: Self.fingerprint(string),
                byteSize: string.utf8.count
            )
        }

        return nil
    }

    private func makeTextClip(from pasteboard: NSPasteboard) -> Clip? {
        guard let string = pasteboard.string(forType: .string) else { return nil }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        let app = NSWorkspace.shared.frontmostApplication
        return Clip(
            kind: Self.detectKind(of: trimmed, bundleID: app?.bundleIdentifier),
            text: string,
            sourceAppName: app?.localizedName,
            sourceBundleID: app?.bundleIdentifier,
            fingerprint: Self.fingerprint(string),
            byteSize: string.utf8.count
        )
    }

    private func captureDroppedText(_ text: String) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        let clip = Clip(
            kind: Self.detectKind(of: trimmed, bundleID: "com.ipaste.drag-drop"),
            text: text,
            sourceAppName: "Drag & Drop",
            sourceBundleID: "com.ipaste.drag-drop",
            fingerprint: Self.fingerprint(text),
            byteSize: text.utf8.count
        )
        _ = storeCapturedClip(clip)
    }

    private func captureDroppedImage(_ image: NSImage) {
        guard let data = image.tiffRepresentation else { return }
        captureImage(image, data: data, sourceAppName: "Drag & Drop", sourceBundleID: "com.ipaste.drag-drop")
    }

    private func captureDroppedFile(_ url: URL) {
        let path = url.path
        let clip = Clip(
            kind: .file,
            text: path,
            sourceAppName: "Drag & Drop",
            sourceBundleID: "com.ipaste.drag-drop",
            fingerprint: Self.fingerprint(path),
            byteSize: fileSize(of: url)
        )
        _ = storeCapturedClip(clip)
    }

    @discardableResult
    private func storeCapturedClip(_ clip: Clip, imageWasChecked: Bool = false) -> Bool {
        if preferences.sensitiveContentProtection,
           clip.kind != .image,
           SensitiveContentDetector.isSensitive(clip.text) {
            onSensitiveCapture?(clip)
            return false
        }
        let stored = store.insert(clip)
        if stored.id != clip.id, let filename = clip.imageFilename {
            store.discardImage(named: filename)
        }
        onCapture?(stored)
        if stored.kind == .image && !imageWasChecked { scheduleOCR(for: stored) }
        return true
    }

    /// OCR before writing an image keeps detected sensitive screenshots out of
    /// the local image directory and history database.
    private func captureImage(
        _ image: NSImage,
        data: Data,
        sourceAppName: String?,
        sourceBundleID: String?,
        createdAt: Date = Date()
    ) {
        let fingerprint = Self.fingerprint(data)
        let dimensions = "\(Int(image.size.width))×\(Int(image.size.height))"

        if store.containsClip(fingerprint: fingerprint) {
            let duplicate = Clip(kind: .image, text: dimensions, sourceAppName: sourceAppName,
                                 sourceBundleID: sourceBundleID, createdAt: createdAt,
                                 fingerprint: fingerprint, byteSize: data.count)
            _ = storeCapturedClip(duplicate, imageWasChecked: true)
            return
        }

        DispatchQueue.global(qos: .utility).async { [weak self] in
            let ocrText = Self.recognizeText(in: data)
            DispatchQueue.main.async { [weak self] in
                guard let self else { return }
                if self.preferences.sensitiveContentProtection,
                   let ocrText,
                   SensitiveContentDetector.isSensitive(ocrText) {
                    let rejected = Clip(kind: .image, text: dimensions, sourceAppName: sourceAppName,
                                        sourceBundleID: sourceBundleID, createdAt: createdAt,
                                        fingerprint: fingerprint, byteSize: data.count)
                    self.onSensitiveCapture?(rejected)
                    return
                }

                guard let filename = self.store.storeImage(image) else { return }
                let clip = Clip(kind: .image, text: dimensions, imageFilename: filename, ocrText: ocrText,
                                sourceAppName: sourceAppName, sourceBundleID: sourceBundleID,
                                createdAt: createdAt, fingerprint: fingerprint, byteSize: data.count)
                _ = self.storeCapturedClip(clip, imageWasChecked: true)
            }
        }
    }

    private func imageFromPasteboard(_ pasteboard: NSPasteboard) -> NSImage? {
        guard let types = pasteboard.types,
              types.contains(where: { [.png, .tiff].contains($0) })
        else { return nil }
        return NSImage(pasteboard: pasteboard)
    }

    /// Backfills OCR for images saved by older versions of the app.
    private func scheduleOCR(for clip: Clip) {
        guard let imageURL = store.imageURL(for: clip) else { return }
        let clipID = clip.id

        DispatchQueue.global(qos: .utility).async { [weak self] in
            guard let data = try? Data(contentsOf: imageURL) else { return }
            let text = Self.recognizeText(in: data)
            DispatchQueue.main.async { [weak self] in
                guard let self else { return }
                if self.preferences.sensitiveContentProtection,
                   let text,
                   SensitiveContentDetector.isSensitive(text),
                   let stored = self.store.clips.first(where: { $0.id == clipID }) {
                    self.store.delete(stored)
                    self.onSensitiveCapture?(stored)
                } else {
                    self.store.setOCRText(text, for: clipID)
                }
            }
        }
    }

    private nonisolated static func recognizeText(in data: Data) -> String? {
        let request = VNRecognizeTextRequest()
        request.recognitionLevel = .accurate
        request.usesLanguageCorrection = true

        let handler = VNImageRequestHandler(data: data, options: [:])
        do {
            try handler.perform([request])
        } catch {
            NSLog("iPaste: OCR failed — \(error.localizedDescription)")
            return nil
        }

        let lines = request.results?.compactMap { observation in
            observation.topCandidates(1).first?.string
        } ?? []
        let text = lines.joined(separator: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return text.isEmpty ? nil : text
    }

    private func fileSize(of url: URL) -> Int {
        (try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0
    }

    // MARK: - Classification

    /// Order matters: color and link are strict tests, code is a heuristic, and
    /// plain text is whatever is left.
    nonisolated static func detectKind(of text: String, bundleID: String?) -> ClipKind {
        if ColorParsing.isPureColor(text) { return .color }
        if isLink(text) { return .link }
        if isCode(text, bundleID: bundleID) { return .code }
        return .text
    }

    private nonisolated static func isLink(_ text: String) -> Bool {
        guard !text.contains(where: \.isWhitespace), text.count < 2048 else { return false }
        guard let url = URL(string: text), let scheme = url.scheme?.lowercased() else { return false }
        return ["http", "https", "ftp", "mailto", "file"].contains(scheme) && url.host != nil
            || scheme == "mailto"
    }

    /// The source app is the strongest signal; for everything else we read the shape.
    private nonisolated static let codeAppBundleIDs: Set<String> = [
        "com.apple.dt.Xcode",
        "com.microsoft.VSCode",
        "com.todesktop.230313mzl4w4u92",   // Cursor
        "dev.zed.Zed",
        "com.apple.Terminal",
        "com.googlecode.iterm2",
        "com.jetbrains.intellij",
        "com.sublimetext.4"
    ]

    private nonisolated static func isCode(_ text: String, bundleID: String?) -> Bool {
        if let bundleID, codeAppBundleIDs.contains(bundleID) { return true }

        let sample = String(text.prefix(2000))
        var score = 0
        if sample.contains("{") && sample.contains("}") { score += 1 }
        if sample.contains(";\n") || sample.hasSuffix(";") { score += 1 }
        if sample.contains("()") || sample.contains("=>") || sample.contains("->") { score += 1 }
        if sample.range(of: #"^\s*(func|def|class|import|const|let|var|public|private|if|for|while)\s"#,
                        options: [.regularExpression]) != nil { score += 2 }
        if sample.contains("\n    ") || sample.contains("\n\t") { score += 1 }
        if sample.hasPrefix("<") && sample.contains(">") { score += 1 }
        return score >= 2
    }

    // MARK: - Fingerprint

    nonisolated static func fingerprint(_ string: String) -> String {
        fingerprint(Data(string.utf8))
    }

    nonisolated static func fingerprint(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
